import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Background from '../assets/background.png'
import Sidebar from '../components/Sidebar.component'

export default function Home() {
  return (
    <>
      <Head>
        <title>Emailgram</title>
        <meta name="description" content="Generated by uy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Image
          src={Background}
          alt="Background"
          layout='fill'
          objectFit='cover'
          sx={{sx: '1'}}
        />
      </div>
      <Sidebar />
    </>
  )
}
